#!/usr/bin/env python3
"""Unifont BDF -> C 헤더 생성 (ASCII 32-127, 8x16 half-width)."""

import pathlib, sys

BDF  = pathlib.Path(__file__).parent.parent / 'res/unifont-17.0.05.bdf'
OUT  = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 \
       else pathlib.Path(__file__).parent.parent / 'src/unifont.h'

def parse(path):
    glyphs = {}
    enc = None
    in_bm = False
    rows = []
    dwidth = None
    for line in open(path):
        line = line.rstrip()
        if line.startswith('ENCODING'):
            enc = int(line.split()[1])
            rows = []
            dwidth = None
            in_bm = False
        elif line.startswith('DWIDTH'):
            dwidth = int(line.split()[1])
        elif line == 'BITMAP':
            in_bm = True
        elif line == 'ENDCHAR':
            if enc is not None and dwidth == 8:
                glyphs[enc] = rows[:16]
            in_bm = False
        elif in_bm and line:
            rows.append(int(line, 16))
    return glyphs

def main():
    glyphs = parse(BDF)
    missing = [cp for cp in range(32, 128) if cp not in glyphs]
    if missing:
        print(f'Warning: missing codepoints: {missing}', file=sys.stderr)

    lines = [
        '/* Auto-generated by tools/gen_font.py from Unifont 17.0.05 */',
        '/* ASCII 32-127, 8x16 half-width glyphs                     */',
        '#pragma once',
        '#include <stdint.h>',
        '',
        'static const uint8_t _font[96][16] = {',
    ]
    for cp in range(32, 128):
        data = glyphs.get(cp, [0]*16)
        row_str = ','.join(f'0x{b:02X}' for b in data)
        lines.append(f'/*{cp:3d}*/ {{{row_str}}},')
    lines += ['};', '']

    OUT.write_text('\n'.join(lines))
    print(f'Written {OUT}  ({96} glyphs)')

if __name__ == '__main__':
    main()
